---
- name: 01 prepare servers playbook
# all (not for manager)
  hosts: "{{my_hosts}}"
  remote_user: root
  # root access
  become: yes  


  tasks:
    - include: 99_prepare-servers-playbook.yml
  
  