---
- name: 04 add nodes to the cluster playbook
# copy file to manager and exec > kk add nodes -f cluster-config-v2.yaml
  hosts: "{{my_hosts}}"
  remote_user: root
  # root access
  become: yes  


  tasks:
  - name: copy config file from manager to server
    template: src=cluster-config-v2.yaml dest=/root/kubekey/cluster-config-v2.yaml

  - name: create cluster
    shell: |
      id
      pwd
      cd /root/kubekey
      yes | kk add nodes -f /root/kubekey/cluster-config-v2.yaml
    register: result

  - debug: msg="{{result.stdout}}"
  - debug: msg="{{result.stderr}}"
