---
- name: 05 del node from cluster playbook
# put config file to manager and exec > kk delete node kworker2 -f cluster-config-v2.yaml 
  hosts: "{{my_hosts}}"
  remote_user: root
  # root access
  become: yes  


  tasks:
  - name: copy config file from manager to server
    template: src=cluster-config-v2.yaml dest=/root/kubekey/cluster-config-v2.yaml

  - name: delete cluster
    shell: yes| kk delete node {{node_name}} -f /root/kubekey/cluster-config-v2.yaml 
    register: result

  - debug: msg="{{result.stdout}}"
  - debug: msg="{{result.stderr}}"
