---
- name: 05 del node from cluster playbook
# put config file to manager and exec > kk delete node kworker2 -f cluster-config-v2.yaml 
  hosts: "{{my_hosts}}"
  remote_user: root
  # root access
  become: yes  

  #vars:
#    service_port: 8080
#    log_path: "/var/log" 

  # vars_files:
  # - vars_ansiblefile.yml

  tasks:
  # - name: Update Red Hat Linux
  #   yum:
  #     name: "*"
  #     state: latest
  #     update_cache: yes
  #   # when: ansible_os_family == "RedHat"

  # - name: download kubekey 
  #   shell: curl -sfL https://get-kk.kubesphere.io | VERSION=v3.0.2 sh -
  #   # when: 1 != 1

  # - name: install kubekey
  #   shell: |
  #     id
  #     mv kk /usr/local/bin/
  #     chmod +x /usr/local/bin/kk 
  #     ln -sf /usr/local/bin/kk /usr/bin/kk
  #     kk version
  #     mkdir -p ~/kubekey
  #     cd ~/kubekey
  #     kk create config
  #   register: installkk
  #   # when: 1 != 1

  # - name: copy config file from manager to server
  #   template: src=cluster-config-v2.yaml dest=/root/kubekey/cluster-config-v2.yaml

# *** kk delete node kworker2 -f cluster-config-v2.yaml ***

  # - name: create cluster
  #   shell: yes | kk create cluster -f cluster-config-v2.yaml
  #   register: createresult

  # - name: check cluster
  #   shell: |
  #     kubectl cluster-info
  #     kubectl get nodes
  #     kubectl get pod -A
  #     kubectl get all -A
  #   register: kubectl-result

  # - debug: msg="{{installkk.stdout}}"
  # - debug: msg="{{installkk.stderr}}"
  # - debug: msg="{{kubectl-result.stdout}}"
  # - debug: msg="{{kubectl-result.stderr}}"
  # - debug: msg="{{createresult.stdout}}"
  # - debug: msg="{{createresult.stderr}}"
