---
- name: 06 delete cluster playbook
# put config file to manager and exec > kk delete cluster -f cluster-config-v2.yaml 
# > kk delete cluster -f cluster-config-v2.yaml -A # Clean and remove all related files 
#   ,e.g. configuration and binary files of kubectl, and kubeadm. 
  hosts: "{{my_hosts}}"
  remote_user: root
  # root access
  become: yes  


  tasks:
  - name: copy config file from manager to server
    template: src=cluster-config-v2.yaml dest=/root/kubekey/cluster-config-v2.yaml

  - name: delete cluster
    shell: yes| kk delete cluster -f /root/kubekey/cluster-config-v2.yaml
    register: result

  - debug: msg="{{result.stdout}}"
  - debug: msg="{{result.stderr}}"
